// Copyright (c) The Thanos Authors.
// Licensed under the Apache License 2.0.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: status/statuspb/rpc.proto

package statuspb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Status_TSDBStatistics_FullMethodName = "/thanos.Status/TSDBStatistics"
)

// StatusClient is the client API for Status service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Status represents the API responsible for gathering status information.
type StatusClient interface {
	// TSDBStatistics has information for all TSDBs.
	TSDBStatistics(ctx context.Context, in *TSDBStatisticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TSDBStatisticsResponse], error)
}

type statusClient struct {
	cc grpc.ClientConnInterface
}

func NewStatusClient(cc grpc.ClientConnInterface) StatusClient {
	return &statusClient{cc}
}

func (c *statusClient) TSDBStatistics(ctx context.Context, in *TSDBStatisticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TSDBStatisticsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Status_ServiceDesc.Streams[0], Status_TSDBStatistics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TSDBStatisticsRequest, TSDBStatisticsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Status_TSDBStatisticsClient = grpc.ServerStreamingClient[TSDBStatisticsResponse]

// StatusServer is the server API for Status service.
// All implementations must embed UnimplementedStatusServer
// for forward compatibility.
//
// Status represents the API responsible for gathering status information.
type StatusServer interface {
	// TSDBStatistics has information for all TSDBs.
	TSDBStatistics(*TSDBStatisticsRequest, grpc.ServerStreamingServer[TSDBStatisticsResponse]) error
	mustEmbedUnimplementedStatusServer()
}

// UnimplementedStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatusServer struct{}

func (UnimplementedStatusServer) TSDBStatistics(*TSDBStatisticsRequest, grpc.ServerStreamingServer[TSDBStatisticsResponse]) error {
	return status.Error(codes.Unimplemented, "method TSDBStatistics not implemented")
}
func (UnimplementedStatusServer) mustEmbedUnimplementedStatusServer() {}
func (UnimplementedStatusServer) testEmbeddedByValue()                {}

// UnsafeStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatusServer will
// result in compilation errors.
type UnsafeStatusServer interface {
	mustEmbedUnimplementedStatusServer()
}

func RegisterStatusServer(s grpc.ServiceRegistrar, srv StatusServer) {
	// If the following call panics, it indicates UnimplementedStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Status_ServiceDesc, srv)
}

func _Status_TSDBStatistics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TSDBStatisticsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatusServer).TSDBStatistics(m, &grpc.GenericServerStream[TSDBStatisticsRequest, TSDBStatisticsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Status_TSDBStatisticsServer = grpc.ServerStreamingServer[TSDBStatisticsResponse]

// Status_ServiceDesc is the grpc.ServiceDesc for Status service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Status_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thanos.Status",
	HandlerType: (*StatusServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TSDBStatistics",
			Handler:       _Status_TSDBStatistics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "status/statuspb/rpc.proto",
}
