{
 "title": "Thanos Compaction",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(thanos_compact_garbage_collected_blocks_total, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Thanos Compact", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operations/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "compaction {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "bucket ops {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_compact_garbage_collections_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "gc ops  {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_compact_group_compactions_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "group compact  {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_compact_sync_meta_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "sync metas  {{instance}}"
    }
   ]
  },
  {
   "title": "Operation Failures/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "compaction {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "bucket ops {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_compact_garbage_collection_failures_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "gc ops  {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_compact_group_compactions_failures_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "group compact  {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_compact_sync_meta_failures_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "sync metas  {{instance}}"
    }
   ]
  },
  {
   "title": "Operation Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_compact_garbage_collection_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance,le))",
     "legendFormat": "99.99 gc {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_compact_sync_meta_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance,le))",
     "legendFormat": "99.99 sync meta  {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance,le))",
     "legendFormat": "99.99 bucket ops {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(prometheus_tsdb_compaction_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance,le))",
     "legendFormat": "99.99 compact {{instance}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\", job=\"thanos-compact\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\", job=\"thanos-compact\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\", job=\"thanos-compact\", quantile=\"1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}