{
 "title": "Thanos Store",
 "tags": [ "thanos" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "labelselector", "query": "${VAR_LABELSELECTOR}" },
   { "name": "labelvalue", "query": "${VAR_LABELVALUE}" }
  ]
 },
 "panels": [
  { "title": "thanos-store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query RPS [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method, kubernetes_namespace)",
     "legendFormat": "{{grpc_code}} {{grpc_method}}  {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Response Time 99.99 Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_server_handling_seconds_bucket{$labelselector=\"$labelvalue\"}[$interval])) by (grpc_method, le, kubernetes_namespace))",
     "legendFormat": "{{grpc_method}} {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Response Size 99.99 Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{$labelselector=\"$labelvalue\"}[$interval])) by (le, kubernetes_namespace))",
     "legendFormat": "{{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Operations/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace, operation)",
     "legendFormat": "bucket {{operation}} {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_drops_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace)",
     "legendFormat": "block drops {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_loads_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace)",
     "legendFormat": "block loads {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Operation Failures/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (operation,kubernetes_namespace)",
     "legendFormat": "bucket {{operation}} {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_drop_failures_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace)",
     "legendFormat": "block drop {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_load_failures_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace)",
     "legendFormat": "block load {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Operation Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace,le, operation))",
     "legendFormat": "99.99 bucket {{operation}} {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace,le))",
     "legendFormat": "99.99 get all {{kubernetes_namespace}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace,le))",
     "legendFormat": "99.99 merge {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Cache Ops/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_items_added_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace,item_type)",
     "legendFormat": "added {{item_type}} {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_items_evicted_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace,item_type)",
     "legendFormat": "evicted {{item_type}} {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_requests_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace,item_type)",
     "legendFormat": "requests {{item_type}} {{kubernetes_namespace}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_hits_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$interval])) by (kubernetes_namespace, item_type)",
     "legendFormat": "hits {{item_type}} {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Pod Operation Time 99th Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_blocks_queried{$labelselector=\"$labelvalue\",quantile=\"0.99\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "blocks queried {{kubernetes_pod_name}} {{kubernetes_namespace}}"
    },
    {
     "expr": "thanos_bucket_store_series_data_fetched{$labelselector=\"$labelvalue\",quantile=\"0.99\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "data fetched {{kubernetes_pod_name}} {{kubernetes_namespace}}"
    },
    {
     "expr": "thanos_bucket_store_series_result_series{$labelselector=\"$labelvalue\",quantile=\"0.99\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "result series {{kubernetes_pod_name}} {{kubernetes_namespace}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{$labelselector=\"$labelvalue\", quantile=\"1\"}",
     "legendFormat": "{{kubernetes_namespace}} {{kubernetes_pod_name}} "
    }
   ]
  }
 ]
}