{
 "title": "Thanos Store",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(grpc_server_handled_total{job=\"thanos-store\"}, instance)"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "thanos-store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query RPS [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{instance=~\"$instance\"}[$interval])) by (grpc_code, grpc_method, instance)",
     "legendFormat": "{{grpc_code}} {{grpc_method}}  {{instance}}"
    }
   ]
  },
  {
   "title": "Response Time 99.99 Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\"}[$interval])) by (grpc_method, le, instance))",
     "legendFormat": "{{grpc_method}} {{instance}}"
    }
   ]
  },
  {
   "title": "Response Size 99.99 Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{instance=~\"$instance\"}[$interval])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operations/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{instance=~\"$instance\"}[$interval])) by (instance, operation)",
     "legendFormat": "bucket {{operation}} {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_drops_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "block drops {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_loads_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "block loads {{instance}}"
    }
   ]
  },
  {
   "title": "Operation Failures/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{instance=~\"$instance\"}[$interval])) by (operation,instance)",
     "legendFormat": "bucket {{operation}} {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_drop_failures_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "block drop {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_block_load_failures_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "block load {{instance}}"
    }
   ]
  },
  {
   "title": "Operation Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance, le, operation))",
     "legendFormat": "99.99 bucket {{operation}} {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance,le))",
     "legendFormat": "99.99 get all {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance,le))",
     "legendFormat": "99.99 merge {{instance}}"
    }
   ]
  },
  {
   "title": "Cache Ops/s [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_items_added_total{instance=~\"$instance\"}[$interval])) by (instance, item_type)",
     "legendFormat": "added {{item_type}} {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_items_evicted_total{instance=~\"$instance\"}[$interval])) by (instance, item_type)",
     "legendFormat": "evicted {{item_type}} {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_requests_total{instance=~\"$instance\"}[$interval])) by (instance, item_type)",
     "legendFormat": "requests {{item_type}} {{instance}}"
    },
    {
     "expr": "sum(rate(thanos_store_index_cache_hits_total{instance=~\"$instance\"}[$interval])) by (instance, item_type)",
     "legendFormat": "hits {{item_type}} {{instance}}"
    }
   ]
  },
  {
   "title": "Operation Time 99th Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_blocks_queried{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "blocks queried {{instance}}"
    },
    {
     "expr": "thanos_bucket_store_series_data_fetched{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "data fetched {{data_type}} {{instance}}"
    },
    {
     "expr": "thanos_bucket_store_series_result_series{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "result series {{instance}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\", job=\"thanos-store\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\", job=\"thanos-store\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\", job=\"thanos-store\", quantile=\"1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}