{
 "title": "Thanos Rule",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(thanos_alert_queue_length, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Thanos Rule", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{instance=~\"$instance\", job=\"thanos-rule\"}[$interval])) by (grpc_code, grpc_method, instance)",
     "legendFormat": "{{grpc_code}}   {{instance}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Query Response Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_server_handling_seconds_bucket{instance=~\"$instance\", job=\"thanos-rule\"}[$interval])) by (grpc_method, le, instance))",
     "legendFormat": "99.99 {{instance}}/{{grpc_method}}"
    }
   ]
  },
  { "title": "Alert Sender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Alerts Sent Rate [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(thanos_alert_sender_alerts_sent_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{alertmanager}}"
    }
   ]
  },
  {
   "title": "Alerts Dropped Rate [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(thanos_alert_sender_alerts_dropped_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{alertmanager}}"
    }
   ]
  },
  {
   "title": "Alert Sender Latency Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_alert_sender_latency_seconds_bucket{instance=~\"$instance\"}[$interval])) by (alertmanager, le, instance))",
     "legendFormat": "99.99 {{instance}}/{{alertmanager}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Compaction Rate [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_total{instance=~\"$instance\", job=\"thanos-rule\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compaction Failure Rate [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\", job=\"thanos-rule\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compaction Duration Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(prometheus_tsdb_compaction_duration_seconds_bucket{instance=~\"$instance\", job=\"thanos-rule\"}[$interval])) by (instance,le))",
     "legendFormat": "99.99 {{instance}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\", job=\"thanos-rule\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\", job=\"thanos-rule\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\", quantile=\"1\", job=\"thanos-rule\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}