# This file contains all available configuration options
# with their default values.

# options for analysis running
version: "2"
run:
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

# output configuration options
output:
  # The formats used to render issues.
  formats:
    text:
      path: stdout
      # print linter name in the end of issue text, default is true
      print-linter-name: true
      # print lines of code with issue, default is true
      print-issued-lines: true

linters:
  # Sorted alphabetically.
  enable:
    - goconst
    - godot
    - misspell
    - promlinter
    - unparam
  settings:
    errcheck:
      # List of functions to exclude from checking, where each entry is a single function to exclude.
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
        - fmt.Fprintln
        - fmt.Fprint
    goconst:
      min-occurrences: 5
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # We don't check metrics naming in the tests.
      - linters:
          - promlinter
        path: _test\.go
      # These are not being checked since these methods exist
      # so that no one else could implement them.
      - linters:
          - unused
        text: SourceStoreAPI.implementsStoreAPI
      - linters:
          - unused
        text: SourceStoreAPI.producesBlocks
      - linters:
          - unused
        text: Source.producesBlocks
      - linters:
          - unused
        text: newMockAlertmanager
      - linters:
          - unused
        text: ruleAndAssert
    # Which dirs to exclude: issues from them won't be reported.
    paths:
      - vendor
      - internal/cortex
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - internal/cortex
      - third_party$
      - builtin$
      - examples$
