go:
  version: 1.25
repository:
  path: github.com/thanos-io/thanos
build:
  binaries:
    - name: thanos
      path: ./cmd/thanos
  flags: -a
  tags:
    all:
      - netgo
      - slicelabels
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
  platforms:
    - darwin/arm64
    - darwin/amd64
    - freebsd/amd64
    - linux/amd64
    - linux/arm64
    - windows/amd64
    - linux/ppc64le
