# Available from https://hub.docker.com/r/circleci/golang/
FROM circleci/golang:1.15 AS builder

ENV GOBIN=/go/bin
ENV BIN_DIR=/go/bin

WORKDIR opt
COPY Makefile .
COPY .bingo ./.bingo
RUN make install-deps

FROM circleci/golang:1.15-node
COPY --from=builder --chown=circleci /go/bin /go/bin/
