module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.26.0

replace github.com/fatih/faillint => github.com/thanos-community/faillint v0.0.0-20250217160734-830c2205d383

require github.com/fatih/faillint v1.15.0

require golang.org/x/sync v0.23.0 // indirect

replace golang.org/x/tools => golang.org/x/tools v0.51.0
