module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	github.com/docopt/docopt-go v0.0.0-20180111231733-ee0de3bc6815 // indirect
	github.com/fatih/color v1.9.0 // indirect
	github.com/kr/text v0.2.0 // indirect
	github.com/raviqqe/liche v0.0.0-20200229003944-f57a5d1c5be4
	github.com/shurcooL/sanitized_anchor_name v1.0.0 // indirect
	github.com/valyala/fasthttp v1.13.1 // indirect
	golang.org/x/net v0.0.0-20200520182314-0ba52f642ac2 // indirect
)
