apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: default
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: thanos
      endpoint: minio.minio.svc.cluster.local:9000
      insecure: true
      access_key: minio
      secret_key: minio123
type: Opaque
