apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: katacode-default
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/part-of: katacode
    app.kubernetes.io/version: master-2020-02-06-b66e0c8
  name: thanos-receive-controller
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - watch
  - get
