name: mixin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Generate
        run: make examples

      - name: Check
        run: make check-examples

  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis) for Jsonnet (mixin)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Format
        run: |
          make jsonnet-format
          git diff --exit-code

      - name: Linting
        run: make jsonnet-lint
