name: mixin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:  
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.22.x

      - name: Generate
        run: make examples

      - name: Check
        run: make check-examples

  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis) for Jsonnet (mixin)
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.22.x

      - name: Format
        run: |
          make jsonnet-format
          git diff --exit-code

      - name: Linting
        run: make jsonnet-lint
